### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by molekylspektroskopi** [illuzn/esphome-april-soil-moisture-sensor#2]
Hi

I managed to get readings from the temperature sensor using this:

```
i2c:
  sda: 08
  scl: 10
  scan: true

sensor:
  - platform: tmp102
    address: 0x48
    update_interval: 5s
    name: "Temperature"
```

It seems that it is not very accurate so I have been playing with offsets using another calibrated temperature sensor.
Was hoping to see if there was any other things I could try to get better readings.

4 out 5 units can find it's temperature sensor for me, but I also had 2 units refusing going to boot mode to accept firmware so they might be a bit finicky
